version: '3.8'

services:
  customer_service:
    build: 
      context: ./customer-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - PYTHONPATH=/app
      - URL_PREFIX=${URL_PREFIX}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    depends_on:
      - customer_db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3

  customer_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_customer:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - customer_service
    restart: always

volumes:
  postgres_data_customer:
