services:
  # movie_service:
  #   build: ./movie-service
  #   command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
  #   volumes:
  #     - ./movie-service/:/app/
  #   ports:
  #     - 8001:8000
  #   environment:
  #     - DATABASE_URI=postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
  #     - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
  #   depends_on:
  #     - movie_db

  # movie_db:
  #   image: postgres:12.1-alpine
  #   volumes:
  #     - postgres_data_movie:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=movie_db_username
  #     - POSTGRES_PASSWORD=movie_db_password
  #     - POSTGRES_DB=movie_db_dev
  
  customer_service:
    build: ./customer-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./customer-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=${DATABASE_URL}
      # - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
    depends_on:
      - customer_db

  customer_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_customer:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=customer_db_username
      - POSTGRES_PASSWORD=customer_db_password
      - POSTGRES_DB=customer_db_dev

  nginx:
    image: nginx:latest
    ports:
      - "8081:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - movie_service
      - customer_service

volumes:
  # postgres_data_movie:
  postgres_data_customer: