version: '3.8'

services:
  customer_service:
    build: ./customer-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./customer-service/:/app/
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - PYTHONPATH=/app
      - URL_PREFIX=${URL_PREFIX}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    depends_on:
      - customer_db

  customer_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_customer:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  nginx:
    image: nginx:latest
    ports:
      - '8081:8080'
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - customer_service

volumes:
  postgres_data_customer:
